language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email:
    recipients: abel.s.siqueira@gmail.com
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - docs # TESTING

jobs:
  include:
    - stage: Documentation
      julia: 1.0
      os: linux
      script:
        - julia --project=docs -e 'using Pkg; Pkg.instantiate(); Pkg.add(PackageSpec(path=pwd()))'
        - julia --project=docs docs/make.jl
    - stage: Coverage
      julia: 1.0
      os: linux
      script: julia -e 'using Pkg; cd(Pkg.dir("NLPModelsJuMP")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
